stages:
- name: Run Script
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: go build
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: busybox/app:v1
      pushRemote: true
      registry: 127.0.0.1:34108
timeout: 60
notification: {}
